Repository psforever/PSF-LoginServer, pull requests merged in 2019-12, with the labels that each got.

#291 Remote Projectiles
  common/src/main/scala/net/psforever/objects/GlobalDefinitions.scala
  common/src/main/scala/net/psforever/objects/ballistics/Projectile.scala
  common/src/main/scala/net/psforever/objects/ballistics/Projectiles.scala
  common/src/main/scala/net/psforever/objects/definition/ProjectileDefinition.scala
  common/src/main/scala/net/psforever/objects/definition/converter/ProjectileConverter.scala
  common/src/main/scala/net/psforever/packet/GamePacketOpcode.scala
  common/src/main/scala/net/psforever/packet/game/DamageFeedbackMessage.scala
  common/src/main/scala/net/psforever/packet/game/DamageMessage.scala
  common/src/main/scala/net/psforever/packet/game/ObjectDetectedMessage.scala
  common/src/main/scala/net/psforever/packet/game/ProjectileStateMessage.scala
  common/src/main/scala/net/psforever/packet/game/objectcreate/ObjectClass.scala
  common/src/main/scala/net/psforever/packet/game/objectcreate/RemoteProjectileData.scala
  common/src/main/scala/net/psforever/packet/game/objectcreate/TrackedProjectileData.scala
  common/src/main/scala/services/avatar/AvatarService.scala
  common/src/main/scala/services/avatar/AvatarServiceMessage.scala
  common/src/main/scala/services/avatar/AvatarServiceResponse.scala
  common/src/test/scala/game/DamageFeedbackMessageTest.scala
  common/src/test/scala/game/DamageMessageTest.scala
  common/src/test/scala/game/ProjectileStateMessageTest.scala
  common/src/test/scala/game/objectcreate/RemoteProjectileDataTest.scala
  common/src/test/scala/game/objectcreate/TrackedProjectileDataTest.scala
  pslogin/src/main/scala/WorldSessionActor.scala
Labels: enhancement, packet

#295 Zone-local Event Systems
  common/src/main/scala/net/psforever/objects/Vehicle.scala
  common/src/main/scala/net/psforever/objects/serverobject/pad/VehicleSpawnControl.scala
  common/src/main/scala/net/psforever/objects/serverobject/pad/VehicleSpawnPad.scala
  common/src/main/scala/net/psforever/objects/serverobject/pad/process/AutoDriveControls.scala
  common/src/main/scala/net/psforever/objects/serverobject/pad/process/VehicleSpawnControlBase.scala
  common/src/main/scala/net/psforever/objects/serverobject/pad/process/VehicleSpawnControlConcealPlayer.scala
  common/src/main/scala/net/psforever/objects/serverobject/pad/process/VehicleSpawnControlDriverControl.scala
  common/src/main/scala/net/psforever/objects/serverobject/pad/process/VehicleSpawnControlFinalClearance.scala
  common/src/main/scala/net/psforever/objects/serverobject/pad/process/VehicleSpawnControlGuided.scala
  common/src/main/scala/net/psforever/objects/serverobject/pad/process/VehicleSpawnControlLoadVehicle.scala
  common/src/main/scala/net/psforever/objects/serverobject/pad/process/VehicleSpawnControlRailJack.scala
  common/src/main/scala/net/psforever/objects/serverobject/pad/process/VehicleSpawnControlSeatDriver.scala
  common/src/main/scala/net/psforever/objects/serverobject/pad/process/VehicleSpawnControlServerVehicleOverride.scala
  common/src/main/scala/net/psforever/objects/serverobject/painbox/PainboxControl.scala
  common/src/main/scala/net/psforever/objects/serverobject/resourcesilo/ResourceSiloControl.scala
  common/src/main/scala/net/psforever/objects/serverobject/structures/Amenity.scala
  common/src/main/scala/net/psforever/objects/serverobject/structures/Building.scala
  common/src/main/scala/net/psforever/objects/serverobject/structures/BuildingControl.scala
  common/src/main/scala/net/psforever/objects/serverobject/terminals/ProximityTerminalControl.scala
  common/src/main/scala/net/psforever/objects/zones/Zone.scala
  common/src/main/scala/net/psforever/objects/zones/ZoneHotSpotProjector.scala
  common/src/main/scala/net/psforever/objects/zones/ZoneVehicleActor.scala
  common/src/main/scala/services/avatar/AvatarService.scala
  common/src/main/scala/services/galaxy/GalaxyAction.scala
  common/src/main/scala/services/galaxy/GalaxyResponse.scala
  common/src/main/scala/services/galaxy/GalaxyService.scala
  common/src/main/scala/services/galaxy/GalaxyServiceMessage.scala
  common/src/main/scala/services/galaxy/GalaxyServiceResponse.scala
  common/src/main/scala/services/local/LocalAction.scala
  common/src/main/scala/services/local/LocalResponse.scala
  common/src/main/scala/services/local/LocalService.scala
  common/src/main/scala/services/local/LocalServiceMessage.scala
  common/src/main/scala/services/local/LocalServiceResponse.scala
  common/src/main/scala/services/vehicle/VehicleAction.scala
  common/src/main/scala/services/vehicle/VehicleResponse.scala
  common/src/main/scala/services/vehicle/VehicleService.scala
  common/src/main/scala/services/vehicle/VehicleServiceMessage.scala
  common/src/main/scala/services/vehicle/VehicleServiceResponse.scala
  common/src/test/scala/objects/AutoDriveControlsTest.scala
  common/src/test/scala/objects/ResourceSiloTest.scala
  common/src/test/scala/objects/VehicleSpawnPadTest.scala
  common/src/test/scala/objects/terminal/ProximityTest.scala
  common/src/test/scala/service/AvatarServiceTest.scala
  common/src/test/scala/service/LocalServiceTest.scala
  common/src/test/scala/service/VehicleServiceTest.scala
  pslogin/src/main/scala/PsLogin.scala
  pslogin/src/main/scala/WorldSessionActor.scala
Labels: enhancement, refactor

#293 Kick players from mountable amenties when owner is hacked
  common/src/main/scala/net/psforever/objects/serverobject/resourcesilo/ResourceSiloControl.scala
  common/src/main/scala/net/psforever/packet/game/PlanetsideAttributeMessage.scala
  pslogin/src/main/scala/WorldSessionActor.scala
Labels: bug, enhancement

#297 MAX Capacitors
  common/src/main/scala/net/psforever/objects/GlobalDefinitions.scala
  common/src/main/scala/net/psforever/objects/Player.scala
  common/src/main/scala/net/psforever/objects/definition/ExoSuitDefinition.scala
  common/src/main/scala/net/psforever/objects/vital/resistance/ResistanceCalculations.scala
  common/src/main/scala/net/psforever/objects/vital/resolution/ResolutionCalculations.scala
  common/src/main/scala/net/psforever/packet/game/GenericActionMessage.scala
  common/src/main/scala/net/psforever/types/CapacitorStateType.scala
  common/src/test/scala/objects/DamageModelTests.scala
  common/src/test/scala/objects/ExoSuitTest.scala
  pslogin/src/main/scala/WorldSessionActor.scala
Labels: enhancement, refactor

#296 Basic lattice functionality
  build.sbt
  common/src/main/scala/net/psforever/objects/serverobject/structures/Building.scala
  common/src/main/scala/net/psforever/objects/serverobject/structures/FoundationBuilder.scala
  common/src/main/scala/net/psforever/objects/serverobject/structures/WarpGate.scala
  common/src/main/scala/net/psforever/objects/zones/Zone.scala
  common/src/main/scala/net/psforever/objects/zones/ZoneMap.scala
  common/src/test/scala/objects/BuildingTest.scala
  common/src/test/scala/objects/DoorTest.scala
  common/src/test/scala/objects/FacilityTurretTest.scala
  common/src/test/scala/objects/FactionAffinityTest.scala
  common/src/test/scala/objects/IFFLockTest.scala
  common/src/test/scala/objects/ResourceSiloTest.scala
  common/src/test/scala/objects/ServerObjectBuilderTest.scala
  common/src/test/scala/objects/VehicleSpawnPadTest.scala
  common/src/test/scala/objects/ZoneTest.scala
  common/src/test/scala/objects/terminal/ImplantTerminalMechTest.scala
  common/src/test/scala/objects/terminal/OrderTerminalTest.scala
  common/src/test/scala/objects/terminal/ProximityTest.scala
  common/src/test/scala/objects/terminal/TerminalControlTest.scala
  pslogin/src/main/scala/zonemaps/Map01.scala
  pslogin/src/main/scala/zonemaps/Map02.scala
  pslogin/src/main/scala/zonemaps/Map03.scala
  pslogin/src/main/scala/zonemaps/Map04.scala
  pslogin/src/main/scala/zonemaps/Map05.scala
  pslogin/src/main/scala/zonemaps/Map06.scala
  pslogin/src/main/scala/zonemaps/Map07.scala
  pslogin/src/main/scala/zonemaps/Map08.scala
  pslogin/src/main/scala/zonemaps/Map09.scala
  pslogin/src/main/scala/zonemaps/Map10.scala
  pslogin/src/main/scala/zonemaps/Map11.scala
  pslogin/src/main/scala/zonemaps/Map12.scala
  pslogin/src/main/scala/zonemaps/Map13.scala
  pslogin/src/main/scala/zonemaps/Map96.scala
  pslogin/src/main/scala/zonemaps/Map97.scala
  pslogin/src/main/scala/zonemaps/Map98.scala
  pslogin/src/main/scala/zonemaps/Map99.scala
Labels: enhancement
