Repository psforever/PSF-LoginServer, pull requests merged in 2020-07, with the labels that each got.

#510 Deployment and NTU
  common/src/main/scala/net/psforever/objects/Deployables.scala
  common/src/main/scala/net/psforever/objects/GlobalDefinitions.scala
  common/src/main/scala/net/psforever/objects/Ntu.scala
  common/src/main/scala/net/psforever/objects/Vehicle.scala
  common/src/main/scala/net/psforever/objects/Vehicles.scala
  common/src/main/scala/net/psforever/objects/definition/VehicleDefinition.scala
  common/src/main/scala/net/psforever/objects/serverobject/damage/DamageableVehicle.scala
  common/src/main/scala/net/psforever/objects/serverobject/deploy/DeploymentBehavior.scala
  common/src/main/scala/net/psforever/objects/serverobject/resourcesilo/ResourceSilo.scala
  common/src/main/scala/net/psforever/objects/serverobject/resourcesilo/ResourceSiloControl.scala
  common/src/main/scala/net/psforever/objects/serverobject/resourcesilo/ResourceSiloDefinition.scala
  common/src/main/scala/net/psforever/objects/serverobject/structures/BuildingDefinition.scala
  common/src/main/scala/net/psforever/objects/serverobject/structures/WarpGate.scala
  common/src/main/scala/net/psforever/objects/serverobject/structures/WarpGateControl.scala
  common/src/main/scala/net/psforever/objects/serverobject/transfer/TransferBehavior.scala
  common/src/main/scala/net/psforever/objects/serverobject/transfer/TransferContainer.scala
  common/src/main/scala/net/psforever/objects/vehicles/AntTransferBehavior.scala
  common/src/main/scala/net/psforever/objects/vehicles/VehicleControl.scala
  common/src/main/scala/net/psforever/types/PlanetSideEmpire.scala
  common/src/main/scala/services/vehicle/VehicleService.scala
  common/src/test/scala/CosmeticsTest.scala
  common/src/test/scala/CryptoPacketTest.scala
  common/src/test/scala/game/ActionProgressMessageTest.scala
  common/src/test/scala/game/CharacterRequestMessageTest.scala
  common/src/test/scala/game/DamageWithPositionMessageTest.scala
  common/src/test/scala/game/HotSpotUpdateMessageTest.scala
  common/src/test/scala/game/ZoneForcedCavernConnectionsMessageTest.scala
  common/src/test/scala/game/objectcreatedetailed/DetailedAmmoBoxDataTest.scala
  common/src/test/scala/game/objectcreatedetailed/DetailedCharacterDataTest.scala
  common/src/test/scala/game/objectcreatedetailed/DetailedCommandDetonaterDataTest.scala
  common/src/test/scala/game/objectcreatedetailed/DetailedREKDataTest.scala
  common/src/test/scala/game/objectcreatedetailed/DetailedWeaponDataTest.scala
  common/src/test/scala/objects/DeployableTest.scala
  common/src/test/scala/objects/DeploymentTest.scala
  common/src/test/scala/objects/EquipmentTest.scala
  common/src/test/scala/objects/ExoSuitTest.scala
  common/src/test/scala/objects/ResourceSiloTest.scala
  common/src/test/scala/objects/UtilityTest.scala
  common/src/test/scala/service/RemoverActorTest.scala
  pslogin/src/main/scala/WorldSessionActor.scala
  pslogin/src/main/scala/Zones.scala
Labels: Refactor

#524 Fix packed binary
  build.sbt
Labels: Bug, Critical

#520 Maelstrom
  common/src/main/scala/net/psforever/objects/GlobalDefinitions.scala
  common/src/main/scala/net/psforever/objects/TurretDeployable.scala
  common/src/main/scala/net/psforever/objects/avatar/PlayerControl.scala
  common/src/main/scala/net/psforever/objects/ballistics/ComplexDeployableSource.scala
  common/src/main/scala/net/psforever/objects/ballistics/DeployableSource.scala
  common/src/main/scala/net/psforever/objects/ballistics/ObjectSource.scala
  common/src/main/scala/net/psforever/objects/ballistics/PlayerSource.scala
  common/src/main/scala/net/psforever/objects/ballistics/SourceEntry.scala
  common/src/main/scala/net/psforever/objects/definition/ExoSuitDefinition.scala
  common/src/main/scala/net/psforever/objects/definition/ProjectileDefinition.scala
  common/src/main/scala/net/psforever/objects/definition/SimpleDeployableDefinition.scala
  common/src/main/scala/net/psforever/objects/definition/VehicleDefinition.scala
  common/src/main/scala/net/psforever/objects/equipment/FireModeDefinition.scala
  common/src/main/scala/net/psforever/objects/serverobject/repair/RepairableEntity.scala
  common/src/main/scala/net/psforever/objects/serverobject/structures/AmenityDefinition.scala
  common/src/main/scala/net/psforever/objects/serverobject/turret/FacilityTurretDefinition.scala
  common/src/main/scala/net/psforever/objects/vital/DamageResistanceModel.scala
  common/src/main/scala/net/psforever/objects/vital/StandardDamages.scala
  common/src/main/scala/net/psforever/objects/vital/VitalityDefinition.scala
  common/src/main/scala/net/psforever/objects/vital/damage/DamageCalculations.scala
  common/src/main/scala/net/psforever/objects/vital/damage/DamageModifiers.scala
  common/src/main/scala/net/psforever/objects/vital/damage/DamageSelection.scala
  common/src/main/scala/net/psforever/objects/vital/resistance/ResistanceProfile.scala
  common/src/main/scala/net/psforever/objects/vital/resolution/DamageResistCalculations.scala
  common/src/main/scala/net/psforever/objects/vital/resolution/ResolutionCalculations.scala
  common/src/main/scala/net/psforever/objects/vital/resolution/ResolutionSelection.scala
  common/src/main/scala/net/psforever/packet/GamePacketOpcode.scala
  common/src/main/scala/net/psforever/packet/game/ChainLashMessage.scala
  common/src/test/scala/game/ChainLashMessageTest.scala
  common/src/test/scala/objects/ConverterTest.scala
  common/src/test/scala/objects/DamageModelTests.scala
  common/src/test/scala/objects/FireModeTest.scala
  pslogin/src/main/scala/WorldSessionActor.scala
Labels: Feature, Low, Packet
