Repository psforever/PSF-LoginServer, pull requests merged in 2021-04, with the labels that each got.

#678 LLUs. 🤯
  src/main/resources/zonemaps/map01.json
  src/main/resources/zonemaps/map02.json
  src/main/resources/zonemaps/map03.json
  src/main/resources/zonemaps/map04.json
  src/main/resources/zonemaps/map05.json
  src/main/resources/zonemaps/map06.json
  src/main/resources/zonemaps/map07.json
  src/main/resources/zonemaps/map08.json
  src/main/resources/zonemaps/map09.json
  src/main/resources/zonemaps/map10.json
  src/main/resources/zonemaps/map96.json
  src/main/resources/zonemaps/map98.json
  src/main/resources/zonemaps/map99.json
  src/main/scala/net/psforever/actors/session/ChatActor.scala
  src/main/scala/net/psforever/actors/session/SessionActor.scala
  src/main/scala/net/psforever/actors/zone/BuildingActor.scala
  src/main/scala/net/psforever/objects/GlobalDefinitions.scala
  src/main/scala/net/psforever/objects/ObjectType.scala
  src/main/scala/net/psforever/objects/avatar/PlayerControl.scala
  src/main/scala/net/psforever/objects/definition/converter/CaptureFlagConverter.scala
  src/main/scala/net/psforever/objects/serverobject/llu/CaptureFlag.scala
  src/main/scala/net/psforever/objects/serverobject/llu/CaptureFlagDefinition.scala
  src/main/scala/net/psforever/objects/serverobject/llu/CaptureFlagSocket.scala
  src/main/scala/net/psforever/objects/serverobject/llu/CaptureFlagSocketDefinition.scala
  src/main/scala/net/psforever/objects/serverobject/structures/AmenityOwner.scala
  src/main/scala/net/psforever/objects/serverobject/structures/Building.scala
  src/main/scala/net/psforever/packet/GamePacketOpcode.scala
  src/main/scala/net/psforever/packet/game/CaptureFlagUpdateMessage.scala
  src/main/scala/net/psforever/packet/game/GenericActionMessage.scala
  src/main/scala/net/psforever/packet/game/GenericObjectActionMessage.scala
  src/main/scala/net/psforever/packet/game/ObjectAttachMessage.scala
  src/main/scala/net/psforever/packet/game/PlanetsideAttributeMessage.scala
  src/main/scala/net/psforever/packet/game/objectcreate/CaptureFlagData.scala
  src/main/scala/net/psforever/services/avatar/AvatarService.scala
  src/main/scala/net/psforever/services/avatar/AvatarServiceMessage.scala
  src/main/scala/net/psforever/services/avatar/AvatarServiceResponse.scala
  src/main/scala/net/psforever/services/galaxy/GalaxyService.scala
  src/main/scala/net/psforever/services/galaxy/GalaxyServiceMessage.scala
  src/main/scala/net/psforever/services/galaxy/GalaxyServiceResponse.scala
  src/main/scala/net/psforever/services/local/LocalService.scala
  src/main/scala/net/psforever/services/local/LocalServiceMessage.scala
  src/main/scala/net/psforever/services/local/LocalServiceResponse.scala
  src/main/scala/net/psforever/services/local/support/CaptureFlagManager.scala
  src/main/scala/net/psforever/services/local/support/HackCaptureActor.scala
  src/main/scala/net/psforever/types/ChatMessageType.scala
  src/main/scala/net/psforever/zones/Zones.scala
  src/test/scala/game/CaptureFlagUpdateMessageTest.scala
  src/test/scala/game/objectcreate/CaptureFlagDataTest.scala
  src/test/scala/objects/PlayerControlTest.scala
Labels: Feature

#740 Minor Squad Refactor
  src/main/scala/net/psforever/actors/net/MiddlewareActor.scala
  src/main/scala/net/psforever/packet/PacketCoding.scala
  src/main/scala/net/psforever/services/teamwork/SquadService.scala
Labels: Refactor

#749 Cargo vehicle Mounting and Gating Fix
  src/main/scala/net/psforever/actors/session/SessionActor.scala
  src/main/scala/net/psforever/objects/Vehicles.scala
  src/main/scala/net/psforever/objects/vehicles/CargoBehavior.scala
  src/main/scala/net/psforever/objects/vehicles/VehicleControl.scala
  src/main/scala/net/psforever/objects/vehicles/VehicleManifest.scala
  src/main/scala/net/psforever/objects/zones/ZoneVehicleActor.scala
Labels: Bug, Should Fix

#751 Flaky Facility Faction Fix
  src/main/scala/net/psforever/actors/session/ChatActor.scala
  src/main/scala/net/psforever/actors/session/SessionActor.scala
  src/main/scala/net/psforever/objects/serverobject/llu/CaptureFlagSocket.scala
  src/main/scala/net/psforever/objects/serverobject/llu/CaptureFlagSocketControl.scala
  src/main/scala/net/psforever/objects/serverobject/resourcesilo/ResourceSilo.scala
  src/main/scala/net/psforever/objects/serverobject/resourcesilo/ResourceSiloControl.scala
  src/main/scala/net/psforever/objects/zones/Zone.scala
  src/main/scala/net/psforever/zones/Zones.scala
Labels: Should Fix

#752 ResetSequence 3
  src/main/scala/net/psforever/actors/net/MiddlewareActor.scala
  src/main/scala/net/psforever/packet/PSPacket.scala
  src/main/scala/net/psforever/packet/PacketCoding.scala
  src/main/scala/net/psforever/packet/ResetSequenceOpcode.scala
  src/main/scala/net/psforever/packet/reset/ResetSequence.scala
  src/test/scala/reset/ResetSequenceTest.scala
Labels: Minor, Needs Reproduction, Packet

#761 Squad Chat Disabled
  src/main/scala/net/psforever/actors/session/ChatActor.scala
  src/main/scala/net/psforever/actors/session/SessionActor.scala
  src/main/scala/net/psforever/objects/teamwork/SquadFeatures.scala
  src/main/scala/net/psforever/services/chat/ChatService.scala
  src/main/scala/net/psforever/services/teamwork/SquadService.scala
Labels: Bug, Medium, Should Fix

#760 Miscellaneous Fixes
  src/main/scala/net/psforever/actors/session/SessionActor.scala
  src/main/scala/net/psforever/objects/avatar/PlayerControl.scala
  src/main/scala/net/psforever/objects/serverobject/damage/DamageableVehicle.scala
Labels: Bug, Medium, Should Fix

#763 A Bad Filter
  server/src/main/java/net/psforever/filters/ApplyCooldownToDuplicateLoggingFilter.java
  src/test/scala/objects/ResourceSiloTest.scala
Labels: Bug, Low, Should Fix

#765 Implant Reset
  src/main/scala/net/psforever/actors/session/SessionActor.scala
Labels: Bug

#768 Leave Squad Service by Character Id
  server/src/main/java/net/psforever/filters/ApplyCooldownToDuplicateLoggingFilter.java
  src/main/scala/net/psforever/actors/session/SessionActor.scala
  src/main/scala/net/psforever/services/teamwork/SquadService.scala
Labels: Bug, Should Fix

#779 Dragon Sunburst
  src/main/scala/net/psforever/objects/vital/projectile/ProjectileDamageModifierFunctions.scala
Labels: Should Fix

#771 Vehicle Cooldown
  src/main/scala/net/psforever/actors/session/AvatarActor.scala
  src/main/scala/net/psforever/actors/session/SessionActor.scala
Labels: Bug, Low

#783 Infiltration Suit Stamina Drain
  src/main/scala/net/psforever/objects/GlobalDefinitions.scala
Labels: Should Fix

#784 Fixes From 20210421 Logs
  src/main/scala/net/psforever/actors/net/LoginActor.scala
  src/main/scala/net/psforever/actors/net/SocketActor.scala
  src/main/scala/net/psforever/actors/session/AvatarActor.scala
  src/main/scala/net/psforever/actors/session/ChatActor.scala
  src/main/scala/net/psforever/actors/session/SessionActor.scala
Labels: Bug, Should Fix

#782 Right Click Locker Swap
  src/main/scala/net/psforever/login/WorldSession.scala
Labels: Bug, Should Fix

#786 Missing Ammunition Types
  src/main/scala/net/psforever/objects/serverobject/terminals/EquipmentTerminalDefinition.scala
Labels: Minor

#800 Spawn Tube Door
  src/main/scala/net/psforever/objects/GlobalDefinitions.scala
  src/main/scala/net/psforever/objects/serverobject/doors/Door.scala
  src/main/scala/net/psforever/objects/serverobject/doors/DoorControl.scala
  src/main/scala/net/psforever/objects/serverobject/doors/DoorDefinition.scala
  src/main/scala/net/psforever/objects/serverobject/doors/SpawnTubeDoor.scala
  src/main/scala/net/psforever/objects/serverobject/doors/SpawnTubeDoorControl.scala
  src/main/scala/net/psforever/zones/Zones.scala
Labels: Feature, Low

#797 Load Vehicle
  server/src/test/scala/actor/objects/VehicleSpawnPadTest.scala
  src/main/scala/net/psforever/actors/session/SessionActor.scala
  src/main/scala/net/psforever/objects/GlobalDefinitions.scala
  src/main/scala/net/psforever/objects/serverobject/pad/VehicleSpawnPad.scala
  src/main/scala/net/psforever/objects/serverobject/pad/process/VehicleSpawnControlLoadVehicle.scala
  src/main/scala/net/psforever/objects/vehicles/AntTransferBehavior.scala
  src/main/scala/net/psforever/services/vehicle/VehicleService.scala
Labels: Low
