Repository psforever/PSF-LoginServer, pull requests merged in 2021-02, with the labels that each got.

#690 No Double Lash
  src/main/scala/net/psforever/objects/vital/resolution/ResolutionCalculations.scala
Labels: Should Fix

#689 Ok Boomer
  server/src/main/resources/overrides/game_objects0.adb.lst
  src/main/scala/net/psforever/actors/session/SessionActor.scala
  src/main/scala/net/psforever/objects/ExplosiveDeployable.scala
  src/main/scala/net/psforever/objects/GlobalDefinitions.scala
  src/main/scala/net/psforever/objects/ballistics/PlayerSource.scala
  src/main/scala/net/psforever/objects/definition/AvatarDefinition.scala
  src/main/scala/net/psforever/objects/definition/ObjectDefinition.scala
  src/main/scala/net/psforever/objects/geometry/Geometry.scala
  src/main/scala/net/psforever/objects/geometry/GeometryForm.scala
  src/main/scala/net/psforever/objects/geometry/PrimitiveShape.scala
  src/main/scala/net/psforever/objects/vital/etc/EmpReason.scala
  src/main/scala/net/psforever/objects/vital/etc/ExplodingEntityReason.scala
  src/main/scala/net/psforever/objects/vital/etc/TriggerUsedReason.scala
  src/main/scala/net/psforever/objects/zones/Zone.scala
  src/main/scala/net/psforever/types/Vector3.scala
  src/main/scala/net/psforever/util/PointOfInterest.scala
  src/test/scala/Vector3Test.scala
  src/test/scala/objects/GeometryTest.scala
Labels: Feature, Medium

#676 Capture terminal logic refactor
  src/main/scala/net/psforever/actors/session/SessionActor.scala
  src/main/scala/net/psforever/actors/zone/BuildingActor.scala
  src/main/scala/net/psforever/objects/GlobalDefinitions.scala
  src/main/scala/net/psforever/objects/Player.scala
  src/main/scala/net/psforever/objects/serverobject/painbox/PainboxControl.scala
  src/main/scala/net/psforever/objects/serverobject/structures/Building.scala
  src/main/scala/net/psforever/objects/serverobject/terminals/CaptureTerminals.scala
  src/main/scala/net/psforever/objects/serverobject/terminals/capture/CaptureTerminal.scala
  src/main/scala/net/psforever/objects/serverobject/terminals/capture/CaptureTerminalAware.scala
  src/main/scala/net/psforever/objects/serverobject/terminals/capture/CaptureTerminalAwareBehavior.scala
  src/main/scala/net/psforever/objects/serverobject/terminals/capture/CaptureTerminalControl.scala
  src/main/scala/net/psforever/objects/serverobject/terminals/capture/CaptureTerminalDefinition.scala
  src/main/scala/net/psforever/objects/serverobject/terminals/capture/CaptureTerminals.scala
  src/main/scala/net/psforever/objects/serverobject/terminals/implant/ImplantTerminalDefinition.scala
  src/main/scala/net/psforever/objects/serverobject/terminals/implant/ImplantTerminalMech.scala
  src/main/scala/net/psforever/objects/serverobject/terminals/implant/ImplantTerminalMechControl.scala
  src/main/scala/net/psforever/objects/serverobject/terminals/implant/ImplantTerminalMechDefinition.scala
  src/main/scala/net/psforever/objects/serverobject/turret/FacilityTurret.scala
  src/main/scala/net/psforever/objects/serverobject/turret/FacilityTurretControl.scala
  src/main/scala/net/psforever/objects/zones/Zone.scala
  src/main/scala/net/psforever/packet/game/PlanetsideAttributeMessage.scala
  src/main/scala/net/psforever/persistence/Implant.scala
  src/main/scala/net/psforever/services/local/LocalService.scala
  src/main/scala/net/psforever/services/local/LocalServiceMessage.scala
  src/main/scala/net/psforever/services/local/LocalServiceResponse.scala
  src/main/scala/net/psforever/services/local/support/HackCaptureActor.scala
  src/main/scala/net/psforever/services/local/support/HackClearActor.scala
  src/main/scala/net/psforever/zones/Zones.scala
  src/test/scala/objects/DamageableTest.scala
  src/test/scala/objects/ServerObjectBuilderTest.scala
  src/test/scala/objects/terminal/ImplantTerminalMechTest.scala
  src/test/scala/service/LocalServiceTest.scala
Labels: Bug, Refactor
